set(_CATKIN_CURRENT_PACKAGE "send_goal_action_loop")
set(send_goal_action_loop_VERSION "0.0.0")
set(send_goal_action_loop_MAINTAINER "ros <ros@todo.todo>")
set(send_goal_action_loop_PACKAGE_FORMAT "2")
set(send_goal_action_loop_BUILD_DEPENDS "actionlib" "move_base_msgs" "roscpp")
set(send_goal_action_loop_BUILD_EXPORT_DEPENDS "actionlib" "move_base_msgs" "roscpp")
set(send_goal_action_loop_BUILDTOOL_DEPENDS "catkin")
set(send_goal_action_loop_BUILDTOOL_EXPORT_DEPENDS )
set(send_goal_action_loop_EXEC_DEPENDS "actionlib" "move_base_msgs" "roscpp")
set(send_goal_action_loop_RUN_DEPENDS "actionlib" "move_base_msgs" "roscpp")
set(send_goal_action_loop_TEST_DEPENDS )
set(send_goal_action_loop_DOC_DEPENDS )
set(send_goal_action_loop_URL_WEBSITE "")
set(send_goal_action_loop_URL_BUGTRACKER "")
set(send_goal_action_loop_URL_REPOSITORY "")
set(send_goal_action_loop_DEPRECATED "")